### ISSUE TITLE
Please upload complete project here

### ISSUE THREAD

**Issue by prashantepic** [ajayJ01/kanyeProject#1]
With All the default folder like app etc... 
plus include all the commands to setup and run the project in readme file in guthub

**Comment by ajayJ01** [comment]
Dear sir,

   I sent project on  ***@***.***

Please check it

**Comment by prashantepic** [comment]
Sorry, but this is not complete code of the project...

**Comment by ajayJ01** [comment]
Dear sir,

Please check this mail : ***@***.***

Zip file attached in this mail please extract that on your system.

**Comment by prashantepic** [comment]
Can you upload project again

**Comment by ajayJ01** [comment]
Sir git support 25 mb only, and my project more then 1 gb. So I'm unable to
upload on git. I can upload on Google drive where you can access.

**Comment by prashantepic** [comment]
Can you please create new project and copy paste the code after creating required files like controller etc. This will save our time.

**Comment by ajayJ01** [comment]
Dear Sir,

As your requirement i create a project and copy paste main files that i use
in my project.
Please check it.
